
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Parser;

import java.util.*;
import java_cup.runtime.*;
import Exception.SyntaxException;
import java.util.ArrayList;
import Lexer.Lexer;
import TablaSimbolo.TablaSimbolo;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class Parser extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return ParserSym.class;
}

  /** Default constructor. */
  @Deprecated
  public Parser() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public Parser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public Parser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\117\000\002\002\004\000\002\002\004\000\002\002" +
    "\003\000\002\004\005\000\002\004\004\000\002\005\004" +
    "\000\002\005\003\000\002\006\005\000\002\007\005\000" +
    "\002\007\003\000\002\003\003\000\002\003\003\000\002" +
    "\003\003\000\002\003\003\000\002\012\005\000\002\012" +
    "\004\000\002\010\004\000\002\010\003\000\002\011\003" +
    "\000\002\011\003\000\002\011\003\000\002\011\003\000" +
    "\002\011\003\000\002\013\005\000\002\014\006\000\002" +
    "\014\010\000\002\014\006\000\002\033\005\000\002\034" +
    "\004\000\002\034\003\000\002\032\003\000\002\032\003" +
    "\000\002\015\011\000\002\015\010\000\002\015\010\000" +
    "\002\037\010\000\002\037\002\000\002\036\004\000\002" +
    "\016\010\000\002\035\010\000\002\035\002\000\002\021" +
    "\005\000\002\021\003\000\002\022\005\000\002\022\003" +
    "\000\002\023\004\000\002\023\003\000\002\030\005\000" +
    "\002\030\005\000\002\030\005\000\002\030\005\000\002" +
    "\030\005\000\002\030\005\000\002\030\003\000\002\024" +
    "\005\000\002\024\005\000\002\024\003\000\002\025\005" +
    "\000\002\025\005\000\002\025\003\000\002\027\004\000" +
    "\002\027\003\000\002\017\005\000\002\017\003\000\002" +
    "\017\003\000\002\017\006\000\002\017\005\000\002\017" +
    "\005\000\002\017\005\000\002\017\003\000\002\031\003" +
    "\000\002\031\003\000\002\031\003\000\002\031\003\000" +
    "\002\026\012\000\002\026\011\000\002\026\010\000\002" +
    "\020\005\000\002\020\003" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\226\000\006\014\010\015\004\001\002\000\014\016" +
    "\220\020\221\021\212\022\217\023\213\001\002\000\004" +
    "\002\uffff\001\002\000\004\002\211\001\002\000\004\014" +
    "\010\001\002\000\020\004\020\007\011\011\026\012\024" +
    "\013\023\017\016\031\022\001\002\000\004\053\176\001" +
    "\002\000\022\004\uffee\007\uffee\011\uffee\012\uffee\013\uffee" +
    "\017\uffee\031\uffee\062\uffee\001\002\000\022\004\uffec\007" +
    "\uffec\011\uffec\012\uffec\013\uffec\017\uffec\031\uffec\062\uffec" +
    "\001\002\000\020\004\ufff0\007\ufff0\011\ufff0\012\ufff0\013" +
    "\ufff0\017\ufff0\031\ufff0\001\002\000\022\004\uffeb\007\uffeb" +
    "\011\uffeb\012\uffeb\013\uffeb\017\uffeb\031\uffeb\062\uffeb\001" +
    "\002\000\004\002\ufff2\001\002\000\022\004\uffef\007\uffef" +
    "\011\uffef\012\uffef\013\uffef\017\uffef\031\uffef\062\uffef\001" +
    "\002\000\004\053\153\001\002\000\020\004\020\007\011" +
    "\011\026\012\024\013\023\017\152\031\022\001\002\000" +
    "\004\047\147\001\002\000\004\053\027\001\002\000\022" +
    "\004\uffe2\007\uffe2\011\uffe2\012\uffe2\013\uffe2\017\uffe2\031" +
    "\uffe2\062\uffe2\001\002\000\022\004\uffed\007\uffed\011\uffed" +
    "\012\uffed\013\uffed\017\uffed\031\uffed\062\uffed\001\002\000" +
    "\022\004\uffe3\007\uffe3\011\uffe3\012\uffe3\013\uffe3\017\uffe3" +
    "\031\uffe3\062\uffe3\001\002\000\034\024\046\025\044\026" +
    "\037\027\050\030\053\031\043\032\036\033\042\034\055" +
    "\036\056\052\035\053\041\063\054\001\002\000\060\004" +
    "\uffbc\007\uffbc\011\uffbc\012\uffbc\013\uffbc\017\uffbc\031\uffbc" +
    "\035\uffbc\036\uffbc\037\uffbc\040\uffbc\041\uffbc\042\uffbc\043" +
    "\uffbc\044\uffbc\045\uffbc\046\uffbc\050\uffbc\051\uffbc\054\uffbc" +
    "\056\uffbc\057\uffbc\062\uffbc\001\002\000\060\004\uffc6\007" +
    "\uffc6\011\uffc6\012\uffc6\013\uffc6\017\uffc6\031\uffc6\035\uffc6" +
    "\036\uffc6\037\uffc6\040\uffc6\041\uffc6\042\uffc6\043\uffc6\044" +
    "\uffc6\045\uffc6\046\uffc6\050\uffc6\051\uffc6\054\uffc6\056\uffc6" +
    "\057\uffc6\062\uffc6\001\002\000\060\004\uffc9\007\uffc9\011" +
    "\uffc9\012\uffc9\013\uffc9\017\uffc9\031\uffc9\035\uffc9\036\uffc9" +
    "\037\136\040\137\041\uffc9\042\uffc9\043\uffc9\044\uffc9\045" +
    "\uffc9\046\uffc9\050\uffc9\051\uffc9\054\uffc9\056\uffc9\057\uffc9" +
    "\062\uffc9\001\002\000\054\004\uffcc\007\uffcc\011\uffcc\012" +
    "\uffcc\013\uffcc\017\uffcc\031\uffcc\035\130\036\127\041\132" +
    "\042\131\043\126\044\125\045\124\046\123\050\uffcc\051" +
    "\uffcc\054\uffcc\056\uffcc\057\uffcc\062\uffcc\001\002\000\060" +
    "\004\uffc4\007\uffc4\011\uffc4\012\uffc4\013\uffc4\017\uffc4\031" +
    "\uffc4\035\uffc4\036\uffc4\037\uffc4\040\uffc4\041\uffc4\042\uffc4" +
    "\043\uffc4\044\uffc4\045\uffc4\046\uffc4\050\uffc4\051\uffc4\054" +
    "\uffc4\056\uffc4\057\uffc4\062\uffc4\001\002\000\032\024\046" +
    "\025\044\026\037\027\050\030\053\031\043\032\036\033" +
    "\042\036\056\052\035\053\041\063\054\001\002\000\060" +
    "\004\uffbb\007\uffbb\011\uffbb\012\uffbb\013\uffbb\017\uffbb\031" +
    "\uffbb\035\uffbb\036\uffbb\037\uffbb\040\uffbb\041\uffbb\042\uffbb" +
    "\043\uffbb\044\uffbb\045\uffbb\046\uffbb\050\uffbb\051\uffbb\054" +
    "\uffbb\056\uffbb\057\uffbb\062\uffbb\001\002\000\004\053\120" +
    "\001\002\000\060\004\uffc1\007\uffc1\011\uffc1\012\uffc1\013" +
    "\uffc1\017\uffc1\031\uffc1\035\uffc1\036\uffc1\037\uffc1\040\uffc1" +
    "\041\uffc1\042\uffc1\043\uffc1\044\uffc1\045\uffc1\046\uffc1\050" +
    "\uffc1\051\uffc1\054\uffc1\056\uffc1\057\uffc1\062\uffc1\001\002" +
    "\000\032\024\046\025\044\026\037\027\050\030\053\031" +
    "\043\032\036\033\042\036\056\052\035\053\041\063\054" +
    "\001\002\000\060\004\uffba\007\uffba\011\uffba\012\uffba\013" +
    "\uffba\017\uffba\031\uffba\035\uffba\036\uffba\037\uffba\040\uffba" +
    "\041\uffba\042\uffba\043\uffba\044\uffba\045\uffba\046\uffba\050" +
    "\uffba\051\uffba\054\uffba\056\uffba\057\uffba\062\uffba\001\002" +
    "\000\062\004\uffc2\007\uffc2\011\uffc2\012\uffc2\013\uffc2\017" +
    "\uffc2\031\uffc2\035\uffc2\036\uffc2\037\uffc2\040\uffc2\041\uffc2" +
    "\042\uffc2\043\uffc2\044\uffc2\045\uffc2\046\uffc2\050\uffc2\051" +
    "\uffc2\054\uffc2\055\113\056\uffc2\057\uffc2\062\uffc2\001\002" +
    "\000\004\053\111\001\002\000\032\004\uffd7\007\uffd7\011" +
    "\uffd7\012\uffd7\013\uffd7\017\uffd7\031\uffd7\051\107\054\uffd7" +
    "\056\uffd7\057\uffd7\062\uffd7\001\002\000\004\053\105\001" +
    "\002\000\004\054\104\001\002\000\060\004\uffb9\007\uffb9" +
    "\011\uffb9\012\uffb9\013\uffb9\017\uffb9\031\uffb9\035\uffb9\036" +
    "\uffb9\037\uffb9\040\uffb9\041\uffb9\042\uffb9\043\uffb9\044\uffb9" +
    "\045\uffb9\046\uffb9\050\uffb9\051\uffb9\054\uffb9\056\uffb9\057" +
    "\uffb9\062\uffb9\001\002\000\034\004\uffd5\007\uffd5\011\uffd5" +
    "\012\uffd5\013\uffd5\017\uffd5\031\uffd5\050\102\051\uffd5\054" +
    "\uffd5\056\uffd5\057\uffd5\062\uffd5\001\002\000\034\004\uffd3" +
    "\007\uffd3\011\uffd3\012\uffd3\013\uffd3\017\uffd3\031\uffd3\050" +
    "\uffd3\051\uffd3\054\uffd3\056\uffd3\057\uffd3\062\uffd3\001\002" +
    "\000\060\004\uffb8\007\uffb8\011\uffb8\012\uffb8\013\uffb8\017" +
    "\uffb8\031\uffb8\035\uffb8\036\uffb8\037\uffb8\040\uffb8\041\uffb8" +
    "\042\uffb8\043\uffb8\044\uffb8\045\uffb8\046\uffb8\050\uffb8\051" +
    "\uffb8\054\uffb8\056\uffb8\057\uffb8\062\uffb8\001\002\000\004" +
    "\053\064\001\002\000\006\054\061\057\060\001\002\000" +
    "\026\024\046\025\044\026\037\027\050\030\053\031\043" +
    "\032\036\033\042\053\041\063\054\001\002\000\060\004" +
    "\uffc5\007\uffc5\011\uffc5\012\uffc5\013\uffc5\017\uffc5\031\uffc5" +
    "\035\uffc5\036\uffc5\037\uffc5\040\uffc5\041\uffc5\042\uffc5\043" +
    "\uffc5\044\uffc5\045\uffc5\046\uffc5\050\uffc5\051\uffc5\054\uffc5" +
    "\056\uffc5\057\uffc5\062\uffc5\001\002\000\032\024\046\025" +
    "\044\026\037\027\050\030\053\031\043\032\036\033\042" +
    "\036\056\052\035\053\041\063\054\001\002\000\022\004" +
    "\uffe7\007\uffe7\011\uffe7\012\uffe7\013\uffe7\017\uffe7\031\uffe7" +
    "\062\uffe7\001\002\000\004\054\063\001\002\000\022\004" +
    "\uffe8\007\uffe8\011\uffe8\012\uffe8\013\uffe8\017\uffe8\031\uffe8" +
    "\062\uffe8\001\002\000\032\024\046\025\044\026\037\027" +
    "\050\030\053\031\043\032\036\033\042\036\056\052\035" +
    "\053\041\063\054\001\002\000\004\057\066\001\002\000" +
    "\034\024\046\025\044\026\037\027\050\030\053\031\043" +
    "\032\036\033\042\036\056\052\035\053\041\055\067\063" +
    "\054\001\002\000\034\024\046\025\044\026\037\027\050" +
    "\030\053\031\043\032\036\033\042\036\056\052\035\053" +
    "\041\056\075\063\054\001\002\000\006\054\073\057\072" +
    "\001\002\000\010\054\uffb3\056\uffb3\057\uffb3\001\002\000" +
    "\032\024\046\025\044\026\037\027\050\030\053\031\043" +
    "\032\036\033\042\036\056\052\035\053\041\063\054\001" +
    "\002\000\060\004\uffb5\007\uffb5\011\uffb5\012\uffb5\013\uffb5" +
    "\017\uffb5\031\uffb5\035\uffb5\036\uffb5\037\uffb5\040\uffb5\041" +
    "\uffb5\042\uffb5\043\uffb5\044\uffb5\045\uffb5\046\uffb5\050\uffb5" +
    "\051\uffb5\054\uffb5\056\uffb5\057\uffb5\062\uffb5\001\002\000" +
    "\010\054\uffb4\056\uffb4\057\uffb4\001\002\000\004\054\101" +
    "\001\002\000\006\056\077\057\072\001\002\000\004\054" +
    "\100\001\002\000\060\004\uffb7\007\uffb7\011\uffb7\012\uffb7" +
    "\013\uffb7\017\uffb7\031\uffb7\035\uffb7\036\uffb7\037\uffb7\040" +
    "\uffb7\041\uffb7\042\uffb7\043\uffb7\044\uffb7\045\uffb7\046\uffb7" +
    "\050\uffb7\051\uffb7\054\uffb7\056\uffb7\057\uffb7\062\uffb7\001" +
    "\002\000\060\004\uffb6\007\uffb6\011\uffb6\012\uffb6\013\uffb6" +
    "\017\uffb6\031\uffb6\035\uffb6\036\uffb6\037\uffb6\040\uffb6\041" +
    "\uffb6\042\uffb6\043\uffb6\044\uffb6\045\uffb6\046\uffb6\050\uffb6" +
    "\051\uffb6\054\uffb6\056\uffb6\057\uffb6\062\uffb6\001\002\000" +
    "\032\024\046\025\044\026\037\027\050\030\053\031\043" +
    "\032\036\033\042\036\056\052\035\053\041\063\054\001" +
    "\002\000\032\004\uffd6\007\uffd6\011\uffd6\012\uffd6\013\uffd6" +
    "\017\uffd6\031\uffd6\051\uffd6\054\uffd6\056\uffd6\057\uffd6\062" +
    "\uffd6\001\002\000\022\004\uffe9\007\uffe9\011\uffe9\012\uffe9" +
    "\013\uffe9\017\uffe9\031\uffe9\062\uffe9\001\002\000\004\054" +
    "\106\001\002\000\060\004\uffbf\007\uffbf\011\uffbf\012\uffbf" +
    "\013\uffbf\017\uffbf\031\uffbf\035\uffbf\036\uffbf\037\uffbf\040" +
    "\uffbf\041\uffbf\042\uffbf\043\uffbf\044\uffbf\045\uffbf\046\uffbf" +
    "\050\uffbf\051\uffbf\054\uffbf\056\uffbf\057\uffbf\062\uffbf\001" +
    "\002\000\032\024\046\025\044\026\037\027\050\030\053" +
    "\031\043\032\036\033\042\036\056\052\035\053\041\063" +
    "\054\001\002\000\030\004\uffd8\007\uffd8\011\uffd8\012\uffd8" +
    "\013\uffd8\017\uffd8\031\uffd8\054\uffd8\056\uffd8\057\uffd8\062" +
    "\uffd8\001\002\000\004\054\112\001\002\000\060\004\uffbe" +
    "\007\uffbe\011\uffbe\012\uffbe\013\uffbe\017\uffbe\031\uffbe\035" +
    "\uffbe\036\uffbe\037\uffbe\040\uffbe\041\uffbe\042\uffbe\043\uffbe" +
    "\044\uffbe\045\uffbe\046\uffbe\050\uffbe\051\uffbe\054\uffbe\056" +
    "\uffbe\057\uffbe\062\uffbe\001\002\000\032\024\046\025\044" +
    "\026\037\027\050\030\053\031\043\032\036\033\042\036" +
    "\056\052\035\053\041\063\054\001\002\000\004\056\115" +
    "\001\002\000\060\004\uffc0\007\uffc0\011\uffc0\012\uffc0\013" +
    "\uffc0\017\uffc0\031\uffc0\035\uffc0\036\uffc0\037\uffc0\040\uffc0" +
    "\041\uffc0\042\uffc0\043\uffc0\044\uffc0\045\uffc0\046\uffc0\050" +
    "\uffc0\051\uffc0\054\uffc0\056\uffc0\057\uffc0\062\uffc0\001\002" +
    "\000\004\054\117\001\002\000\060\004\uffc3\007\uffc3\011" +
    "\uffc3\012\uffc3\013\uffc3\017\uffc3\031\uffc3\035\uffc3\036\uffc3" +
    "\037\uffc3\040\uffc3\041\uffc3\042\uffc3\043\uffc3\044\uffc3\045" +
    "\uffc3\046\uffc3\050\uffc3\051\uffc3\054\uffc3\056\uffc3\057\uffc3" +
    "\062\uffc3\001\002\000\004\054\121\001\002\000\060\004" +
    "\uffbd\007\uffbd\011\uffbd\012\uffbd\013\uffbd\017\uffbd\031\uffbd" +
    "\035\uffbd\036\uffbd\037\uffbd\040\uffbd\041\uffbd\042\uffbd\043" +
    "\uffbd\044\uffbd\045\uffbd\046\uffbd\050\uffbd\051\uffbd\054\uffbd" +
    "\056\uffbd\057\uffbd\062\uffbd\001\002\000\034\004\uffd4\007" +
    "\uffd4\011\uffd4\012\uffd4\013\uffd4\017\uffd4\031\uffd4\050\uffd4" +
    "\051\uffd4\054\uffd4\056\uffd4\057\uffd4\062\uffd4\001\002\000" +
    "\030\024\046\025\044\026\037\027\050\030\053\031\043" +
    "\032\036\033\042\036\056\053\041\063\054\001\002\000" +
    "\030\024\046\025\044\026\037\027\050\030\053\031\043" +
    "\032\036\033\042\036\056\053\041\063\054\001\002\000" +
    "\030\024\046\025\044\026\037\027\050\030\053\031\043" +
    "\032\036\033\042\036\056\053\041\063\054\001\002\000" +
    "\030\024\046\025\044\026\037\027\050\030\053\031\043" +
    "\032\036\033\042\036\056\053\041\063\054\001\002\000" +
    "\030\024\046\025\044\026\037\027\050\030\053\031\043" +
    "\032\036\033\042\036\056\053\041\063\054\001\002\000" +
    "\030\024\046\025\044\026\037\027\050\030\053\031\043" +
    "\032\036\033\042\036\056\053\041\063\054\001\002\000" +
    "\030\024\046\025\044\026\037\027\050\030\053\031\043" +
    "\032\036\033\042\036\056\053\041\063\054\001\002\000" +
    "\030\024\046\025\044\026\037\027\050\030\053\031\043" +
    "\032\036\033\042\036\056\053\041\063\054\001\002\000" +
    "\040\004\uffd2\007\uffd2\011\uffd2\012\uffd2\013\uffd2\017\uffd2" +
    "\031\uffd2\035\130\036\127\050\uffd2\051\uffd2\054\uffd2\056" +
    "\uffd2\057\uffd2\062\uffd2\001\002\000\040\004\uffd1\007\uffd1" +
    "\011\uffd1\012\uffd1\013\uffd1\017\uffd1\031\uffd1\035\130\036" +
    "\127\050\uffd1\051\uffd1\054\uffd1\056\uffd1\057\uffd1\062\uffd1" +
    "\001\002\000\060\004\uffcb\007\uffcb\011\uffcb\012\uffcb\013" +
    "\uffcb\017\uffcb\031\uffcb\035\uffcb\036\uffcb\037\136\040\137" +
    "\041\uffcb\042\uffcb\043\uffcb\044\uffcb\045\uffcb\046\uffcb\050" +
    "\uffcb\051\uffcb\054\uffcb\056\uffcb\057\uffcb\062\uffcb\001\002" +
    "\000\030\024\046\025\044\026\037\027\050\030\053\031" +
    "\043\032\036\033\042\036\056\053\041\063\054\001\002" +
    "\000\030\024\046\025\044\026\037\027\050\030\053\031" +
    "\043\032\036\033\042\036\056\053\041\063\054\001\002" +
    "\000\060\004\uffc7\007\uffc7\011\uffc7\012\uffc7\013\uffc7\017" +
    "\uffc7\031\uffc7\035\uffc7\036\uffc7\037\uffc7\040\uffc7\041\uffc7" +
    "\042\uffc7\043\uffc7\044\uffc7\045\uffc7\046\uffc7\050\uffc7\051" +
    "\uffc7\054\uffc7\056\uffc7\057\uffc7\062\uffc7\001\002\000\060" +
    "\004\uffc8\007\uffc8\011\uffc8\012\uffc8\013\uffc8\017\uffc8\031" +
    "\uffc8\035\uffc8\036\uffc8\037\uffc8\040\uffc8\041\uffc8\042\uffc8" +
    "\043\uffc8\044\uffc8\045\uffc8\046\uffc8\050\uffc8\051\uffc8\054" +
    "\uffc8\056\uffc8\057\uffc8\062\uffc8\001\002\000\060\004\uffca" +
    "\007\uffca\011\uffca\012\uffca\013\uffca\017\uffca\031\uffca\035" +
    "\uffca\036\uffca\037\136\040\137\041\uffca\042\uffca\043\uffca" +
    "\044\uffca\045\uffca\046\uffca\050\uffca\051\uffca\054\uffca\056" +
    "\uffca\057\uffca\062\uffca\001\002\000\040\004\uffce\007\uffce" +
    "\011\uffce\012\uffce\013\uffce\017\uffce\031\uffce\035\130\036" +
    "\127\050\uffce\051\uffce\054\uffce\056\uffce\057\uffce\062\uffce" +
    "\001\002\000\040\004\uffcd\007\uffcd\011\uffcd\012\uffcd\013" +
    "\uffcd\017\uffcd\031\uffcd\035\130\036\127\050\uffcd\051\uffcd" +
    "\054\uffcd\056\uffcd\057\uffcd\062\uffcd\001\002\000\040\004" +
    "\uffd0\007\uffd0\011\uffd0\012\uffd0\013\uffd0\017\uffd0\031\uffd0" +
    "\035\130\036\127\050\uffd0\051\uffd0\054\uffd0\056\uffd0\057" +
    "\uffd0\062\uffd0\001\002\000\040\004\uffcf\007\uffcf\011\uffcf" +
    "\012\uffcf\013\uffcf\017\uffcf\031\uffcf\035\130\036\127\050" +
    "\uffcf\051\uffcf\054\uffcf\056\uffcf\057\uffcf\062\uffcf\001\002" +
    "\000\032\024\046\025\044\026\037\027\050\030\053\031" +
    "\043\032\036\033\042\036\056\052\035\053\041\063\054" +
    "\001\002\000\022\004\uffea\007\uffea\011\uffea\012\uffea\013" +
    "\uffea\017\uffea\031\uffea\062\uffea\001\002\000\020\004\ufff1" +
    "\007\ufff1\011\ufff1\012\ufff1\013\ufff1\017\ufff1\031\ufff1\001" +
    "\002\000\004\002\ufff3\001\002\000\032\024\046\025\044" +
    "\026\037\027\050\030\053\031\043\032\036\033\042\036" +
    "\056\052\035\053\041\063\054\001\002\000\004\054\155" +
    "\001\002\000\004\061\157\001\002\000\026\004\uffdd\005" +
    "\uffdd\006\165\007\uffdd\011\uffdd\012\uffdd\013\uffdd\017\uffdd" +
    "\031\uffdd\062\uffdd\001\002\000\016\004\020\007\011\011" +
    "\026\012\024\013\023\031\022\001\002\000\020\004\uffe4" +
    "\007\uffe4\011\uffe4\012\uffe4\013\uffe4\031\uffe4\062\uffe4\001" +
    "\002\000\020\004\020\007\011\011\026\012\024\013\023" +
    "\031\022\062\162\001\002\000\030\004\uffe6\005\uffe6\006" +
    "\uffe6\007\uffe6\010\uffe6\011\uffe6\012\uffe6\013\uffe6\017\uffe6" +
    "\031\uffe6\062\uffe6\001\002\000\020\004\uffe5\007\uffe5\011" +
    "\uffe5\012\uffe5\013\uffe5\031\uffe5\062\uffe5\001\002\000\026" +
    "\004\uffdf\005\170\006\165\007\uffdf\011\uffdf\012\uffdf\013" +
    "\uffdf\017\uffdf\031\uffdf\062\uffdf\001\002\000\004\061\157" +
    "\001\002\000\022\004\uffe0\007\uffe0\011\uffe0\012\uffe0\013" +
    "\uffe0\017\uffe0\031\uffe0\062\uffe0\001\002\000\022\004\uffdc" +
    "\007\uffdc\011\uffdc\012\uffdc\013\uffdc\017\uffdc\031\uffdc\062" +
    "\uffdc\001\002\000\004\053\172\001\002\000\022\004\uffe1" +
    "\007\uffe1\011\uffe1\012\uffe1\013\uffe1\017\uffe1\031\uffe1\062" +
    "\uffe1\001\002\000\032\024\046\025\044\026\037\027\050" +
    "\030\053\031\043\032\036\033\042\036\056\052\035\053" +
    "\041\063\054\001\002\000\004\054\174\001\002\000\004" +
    "\061\157\001\002\000\026\004\uffde\005\uffde\006\uffde\007" +
    "\uffde\011\uffde\012\uffde\013\uffde\017\uffde\031\uffde\062\uffde" +
    "\001\002\000\032\024\046\025\044\026\037\027\050\030" +
    "\053\031\043\032\036\033\042\036\056\052\035\053\041" +
    "\063\054\001\002\000\004\054\200\001\002\000\004\061" +
    "\157\001\002\000\024\004\uffd9\007\uffd9\010\uffd9\011\uffd9" +
    "\012\uffd9\013\uffd9\017\uffd9\031\uffd9\062\uffd9\001\002\000" +
    "\024\004\uffdb\007\uffdb\010\203\011\uffdb\012\uffdb\013\uffdb" +
    "\017\uffdb\031\uffdb\062\uffdb\001\002\000\004\053\204\001" +
    "\002\000\032\024\046\025\044\026\037\027\050\030\053" +
    "\031\043\032\036\033\042\036\056\052\035\053\041\063" +
    "\054\001\002\000\004\054\206\001\002\000\004\061\157" +
    "\001\002\000\024\004\uffda\007\uffda\010\uffda\011\uffda\012" +
    "\uffda\013\uffda\017\uffda\031\uffda\062\uffda\001\002\000\004" +
    "\002\000\001\002\000\004\002\001\001\002\000\004\060" +
    "\ufff6\001\002\000\004\060\ufff4\001\002\000\014\016\227" +
    "\020\221\021\212\022\217\023\213\001\002\000\004\060" +
    "\222\001\002\000\014\016\ufffb\020\ufffb\021\ufffb\022\ufffb" +
    "\023\ufffb\001\002\000\004\060\ufff5\001\002\000\004\014" +
    "\ufffd\001\002\000\004\060\ufff7\001\002\000\004\031\223" +
    "\001\002\000\016\016\ufff8\020\ufff8\021\ufff8\022\ufff8\023" +
    "\ufff8\057\ufff8\001\002\000\016\016\ufffa\020\ufffa\021\ufffa" +
    "\022\ufffa\023\ufffa\057\225\001\002\000\004\031\226\001" +
    "\002\000\016\016\ufff9\020\ufff9\021\ufff9\022\ufff9\023\ufff9" +
    "\057\ufff9\001\002\000\004\014\ufffe\001\002\000\014\016" +
    "\ufffc\020\ufffc\021\ufffc\022\ufffc\023\ufffc\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\226\000\010\002\005\004\006\012\004\001\001\000" +
    "\010\003\214\005\213\006\215\001\001\000\002\001\001" +
    "\000\002\001\001\000\004\012\207\001\001\000\020\010" +
    "\020\011\013\013\016\014\011\015\024\016\012\032\014" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\016\011\150\013" +
    "\016\014\011\015\024\016\012\032\014\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\026\017\033\021\046\022\044" +
    "\023\050\024\032\025\031\026\027\027\030\030\051\031" +
    "\037\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\022\017" +
    "\033\023\121\024\032\025\031\026\027\027\030\030\051" +
    "\031\037\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\026\017\033\021\115\022\044\023\050" +
    "\024\032\025\031\026\027\027\030\030\051\031\037\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\010\017" +
    "\056\026\027\031\037\001\001\000\002\001\001\000\026" +
    "\017\033\021\061\022\044\023\050\024\032\025\031\026" +
    "\027\027\030\030\051\031\037\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\026\017\033\021" +
    "\064\022\044\023\050\024\032\025\031\026\027\027\030" +
    "\030\051\031\037\001\001\000\002\001\001\000\030\017" +
    "\033\020\067\021\070\022\044\023\050\024\032\025\031" +
    "\026\027\027\030\030\051\031\037\001\001\000\030\017" +
    "\033\020\075\021\070\022\044\023\050\024\032\025\031" +
    "\026\027\027\030\030\051\031\037\001\001\000\002\001" +
    "\001\000\002\001\001\000\026\017\033\021\073\022\044" +
    "\023\050\024\032\025\031\026\027\027\030\030\051\031" +
    "\037\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\024\017\033\022\102\023\050" +
    "\024\032\025\031\026\027\027\030\030\051\031\037\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\026\017\033\021\107\022\044\023" +
    "\050\024\032\025\031\026\027\027\030\030\051\031\037" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\026\017\033\021\113\022\044\023\050\024\032" +
    "\025\031\026\027\027\030\030\051\031\037\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\016\017\033\024\145\025\031\026\027\027\030" +
    "\031\037\001\001\000\016\017\033\024\144\025\031\026" +
    "\027\027\030\031\037\001\001\000\016\017\033\024\143" +
    "\025\031\026\027\027\030\031\037\001\001\000\016\017" +
    "\033\024\142\025\031\026\027\027\030\031\037\001\001" +
    "\000\014\017\033\025\141\026\027\027\030\031\037\001" +
    "\001\000\014\017\033\025\134\026\027\027\030\031\037" +
    "\001\001\000\016\017\033\024\133\025\031\026\027\027" +
    "\030\031\037\001\001\000\016\017\033\024\132\025\031" +
    "\026\027\027\030\031\037\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\012\017\033\026\027" +
    "\027\140\031\037\001\001\000\012\017\033\026\027\027" +
    "\137\031\037\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\026\017\033\021\147" +
    "\022\044\023\050\024\032\025\031\026\027\027\030\030" +
    "\051\031\037\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\026\017\033\021\153\022\044\023" +
    "\050\024\032\025\031\026\027\027\030\030\051\031\037" +
    "\001\001\000\002\001\001\000\004\033\155\001\001\000" +
    "\006\036\165\037\163\001\001\000\020\011\157\013\016" +
    "\014\011\015\024\016\012\032\014\034\160\001\001\000" +
    "\002\001\001\000\016\011\162\013\016\014\011\015\024" +
    "\016\012\032\014\001\001\000\002\001\001\000\002\001" +
    "\001\000\004\036\170\001\001\000\004\033\166\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\026\017\033\021\172\022\044\023\050" +
    "\024\032\025\031\026\027\027\030\030\051\031\037\001" +
    "\001\000\002\001\001\000\004\033\174\001\001\000\002" +
    "\001\001\000\026\017\033\021\176\022\044\023\050\024" +
    "\032\025\031\026\027\027\030\030\051\031\037\001\001" +
    "\000\002\001\001\000\004\033\200\001\001\000\004\035" +
    "\201\001\001\000\002\001\001\000\002\001\001\000\026" +
    "\017\033\021\204\022\044\023\050\024\032\025\031\026" +
    "\027\027\030\030\051\031\037\001\001\000\002\001\001" +
    "\000\004\033\206\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\006\003\214\006\227\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\007\223\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$Parser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$Parser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$Parser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



    TablaSimbolo tablaSimbolos = Lexer.tablaSimbolos;

    public void syntax_error(Symbol s){
        // Esto solo imprime un aviso temporal en consola
        System.out.println("Aviso: Error sintáctico cerca de la línea " + (s.left + 1));
    }

    public void unrecovered_syntax_error(Symbol s) throws java.lang.Exception{
        // Construimos el mensaje y LANZAMOS la excepción
        String mensaje = "Error en la linea " + (s.left + 1) + " Columna " + s.right + ". Valor simbolo '" + s.value + "' no esperado.";

        // Lanzamos la excepción directamente
        throw new SyntaxException(mensaje);
    }


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$Parser$actions {
  private final Parser parser;

  /** Constructor */
  CUP$Parser$actions(Parser parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$Parser$do_action_part00000000(
    int                        CUP$Parser$act_num,
    java_cup.runtime.lr_parser CUP$Parser$parser,
    java.util.Stack            CUP$Parser$stack,
    int                        CUP$Parser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$Parser$result;

      /* select the action based on the action number */
      switch (CUP$Parser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= program EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		String start_val = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		RESULT = start_val;
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$Parser$parser.done_parsing();
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // program ::= seccion_declaracion seccion_sentencias 
            {
              String RESULT =null;
		int bdleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int bdright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		String bd = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		int bsleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int bsright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String bs = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
            RESULT = bd + "\n" + bs; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("program",0, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // program ::= seccion_sentencias 
            {
              String RESULT =null;
		int bsleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int bsright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String bs = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
             RESULT= bs; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("program",0, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // seccion_declaracion ::= DECLARE bloque_declaraciones FIN_DECLARE 
            {
              String RESULT =null;
		int bdleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int bdright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		String bd = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		
                    RESULT = bd; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("seccion_declaracion",2, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // seccion_declaracion ::= DECLARE FIN_DECLARE 
            {
              String RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("seccion_declaracion",2, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // bloque_declaraciones ::= bloque_declaraciones declaracion 
            {
              String RESULT =null;
		int bdleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int bdright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		String bd = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		int dleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int dright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String d = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
                        RESULT = bd + "\n" + d;
                      
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("bloque_declaraciones",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // bloque_declaraciones ::= declaracion 
            {
              String RESULT =null;
		int dleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int dright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String d = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
                        RESULT = d;
                       
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("bloque_declaraciones",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // declaracion ::= tipo DOS_PUNTOS lista_ids 
            {
              String RESULT =null;
		int tleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int tright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		String t = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int lleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int lright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		ArrayList<String> l = (ArrayList<String>)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
            // Recorremos la lista y seteamos el tipo en la tabla
            for (String id : l) {
                tablaSimbolos.setType(id, t);
            }
            RESULT = t + " : " + l.toString();
        
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("declaracion",4, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // lista_ids ::= lista_ids COMA ID 
            {
              ArrayList<String> RESULT =null;
		int lleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		ArrayList<String> l = (ArrayList<String>)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int idleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
            l.add(id);
            RESULT = l;
        
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("lista_ids",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // lista_ids ::= ID 
            {
              ArrayList<String> RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
            ArrayList<String> lista = new ArrayList<>();
            lista.add(id);
            RESULT = lista;
        
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("lista_ids",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // tipo ::= TYPE_INT 
            {
              String RESULT =null;
		 RESULT = "INT"; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("tipo",1, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // tipo ::= TYPE_FLOAT 
            {
              String RESULT =null;
		 RESULT = "FLOAT"; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("tipo",1, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // tipo ::= TYPE_BOOL 
            {
              String RESULT =null;
		 RESULT = "BOOL"; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("tipo",1, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // tipo ::= TYPE_ARRAY 
            {
              String RESULT =null;
		 RESULT = "FLOAT_ARRAY"; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("tipo",1, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // seccion_sentencias ::= PROGRAM bloque_sentencias FIN_PROGRAM 
            {
              String RESULT =null;
		int bsleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int bsright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		String bs = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		
                    RESULT = bs;
                    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("seccion_sentencias",8, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // seccion_sentencias ::= PROGRAM FIN_PROGRAM 
            {
              String RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("seccion_sentencias",8, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // bloque_sentencias ::= bloque_sentencias sentencia 
            {
              String RESULT =null;
		int bsleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int bsright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		String bs = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		int sleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String s = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
                   RESULT = bs + "\n" + s;
                   
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("bloque_sentencias",6, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // bloque_sentencias ::= sentencia 
            {
              String RESULT =null;
		int sleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String s = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
                   RESULT = s;
                    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("bloque_sentencias",6, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // sentencia ::= asignacion 
            {
              String RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String a = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
            RESULT= a;
          
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("sentencia",7, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // sentencia ::= impresion 
            {
              String RESULT =null;
		int ileft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int iright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String i = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
            RESULT= i;
          
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("sentencia",7, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // sentencia ::= sentencia_if 
            {
              String RESULT =null;
		int sileft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int siright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String si = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
            RESULT= si;
          
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("sentencia",7, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // sentencia ::= sentencia_while 
            {
              String RESULT =null;
		int swleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int swright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String sw = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
            RESULT= sw;
          
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("sentencia",7, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // sentencia ::= sentencia_control 
            {
              String RESULT =null;
		int scleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int scright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String sc = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
            RESULT= sc;
          
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("sentencia",7, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // asignacion ::= ID ASIG expresionOr 
            {
              String RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String e = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
              RESULT= e;
            
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("asignacion",9, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // impresion ::= PRINT PAR_A expresionOr PAR_C 
            {
              String RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		String e = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		
             RESULT = e;
           
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("impresion",10, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // impresion ::= PRINT PAR_A CTE_STR COMA expresionOr PAR_C 
            {
              String RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		String e = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		
             RESULT = e;
           
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("impresion",10, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // impresion ::= PRINT PAR_A CTE_STR PAR_C 
            {
              String RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("impresion",10, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // bloque ::= INDENT lista_sentencias DEDENT 
            {
              String RESULT =null;
		int lsleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int lsright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		String ls = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		
                  RESULT = ls;
                  
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("bloque",25, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // lista_sentencias ::= lista_sentencias sentencia 
            {
              String RESULT =null;
		int lsleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int lsright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		String ls = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		int sleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String s = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT= ls + "\n" + s;
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("lista_sentencias",26, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // lista_sentencias ::= sentencia 
            {
              String RESULT =null;
		int sleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String s = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		RESULT = s;
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("lista_sentencias",26, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // sentencia_control ::= BREAK 
            {
              String RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("sentencia_control",24, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // sentencia_control ::= CONTINUE 
            {
              String RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("sentencia_control",24, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // sentencia_if ::= IF PAR_A expresionOr PAR_C bloque elif_part else_part 
            {
              String RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)).right;
		String c = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-4)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int bright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		String b = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int elleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int elright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		String el = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		int esleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int esright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String es = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT= c + "\n" + b + "\n" + el + "\n" + es ;
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("sentencia_if",11, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-6)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // sentencia_if ::= IF PAR_A expresionOr PAR_C bloque else_part 
            {
              String RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).right;
		String c = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-3)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int bright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		String b = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		int esleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int esright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String es = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT= c + "\n" + b + "\n" + es ;
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("sentencia_if",11, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // sentencia_if ::= IF PAR_A expresionOr PAR_C bloque elif_part 
            {
              String RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).right;
		String c = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-3)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int bright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		String b = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		int elleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int elright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String el = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT= c + "\n" + b + "\n" + el ;
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("sentencia_if",11, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // elif_part ::= elif_part ELIF PAR_A expresionOr PAR_C bloque 
            {
              String RESULT =null;
		int elleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)).left;
		int elright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)).right;
		String el = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-5)).value;
		int cleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		String c = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String b = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT= el + "\n" + c + "\n" + b;
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("elif_part",29, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // elif_part ::= 
            {
              String RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("elif_part",29, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // else_part ::= ELSE bloque 
            {
              String RESULT =null;
		int bleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String b = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT= b;
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("else_part",28, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // sentencia_while ::= WHILE PAR_A expresionOr PAR_C bloque alt_while_part 
            {
              String RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).right;
		String c = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-3)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int bright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		String b = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		int awleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int awright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String aw = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT= c + "\n" + b + "\n" + aw ;
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("sentencia_while",12, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // alt_while_part ::= alt_while_part ALT_WHILE PAR_A expresionOr PAR_C bloque 
            {
              String RESULT =null;
		int awleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)).left;
		int awright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)).right;
		String aw = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-5)).value;
		int cleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		String c = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String b = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT= aw + "\n" + c + "\n" + b ;
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("alt_while_part",27, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // alt_while_part ::= 
            {
              String RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("alt_while_part",27, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // expresionOr ::= expresionAnd OR expresionOr 
            {
              String RESULT =null;
		int ealeft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int earight = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		String ea = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int eoleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int eoright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String eo = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
              RESULT = ea + "\n" + eo;
            
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresionOr",15, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // expresionOr ::= expresionAnd 
            {
              String RESULT =null;
		int ealeft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int earight = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String ea = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
              RESULT = ea;
            
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresionOr",15, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // expresionAnd ::= expresionNot AND expresionAnd 
            {
              String RESULT =null;
		int enleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int enright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		String en = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int ealeft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int earight = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String ea = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
              RESULT = en + "\n" + ea;
            
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresionAnd",16, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // expresionAnd ::= expresionNot 
            {
              String RESULT =null;
		int enleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int enright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String en = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
              RESULT = en;
            
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresionAnd",16, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // expresionNot ::= NOT expresionNot 
            {
              String RESULT =null;
		int enleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int enright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String en = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
               RESULT = en ;
             
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresionNot",17, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // expresionNot ::= comparacion 
            {
              String RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int cright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String c = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
               RESULT= c;
             
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresionNot",17, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // comparacion ::= expresionSumRes COMP_IGUAL expresionSumRes 
            {
              String RESULT =null;
		int es1left = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int es1right = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		String es1 = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int es2left = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int es2right = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String es2 = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = es1 + "\n" + es2;
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("comparacion",22, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 48: // comparacion ::= expresionSumRes COMP_DISTINTO expresionSumRes 
            {
              String RESULT =null;
		int es1left = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int es1right = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		String es1 = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int es2left = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int es2right = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String es2 = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = es1 + "\n" + es2;
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("comparacion",22, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 49: // comparacion ::= expresionSumRes COMP_MAYOR expresionSumRes 
            {
              String RESULT =null;
		int es1left = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int es1right = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		String es1 = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int es2left = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int es2right = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String es2 = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = es1 + "\n" + es2;
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("comparacion",22, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 50: // comparacion ::= expresionSumRes COMP_MENOR expresionSumRes 
            {
              String RESULT =null;
		int es1left = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int es1right = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		String es1 = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int es2left = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int es2right = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String es2 = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = es1 + "\n" + es2;
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("comparacion",22, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 51: // comparacion ::= expresionSumRes COMP_MAYOR_IGUAL expresionSumRes 
            {
              String RESULT =null;
		int es1left = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int es1right = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		String es1 = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int es2left = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int es2right = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String es2 = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = es1 + "\n" + es2;
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("comparacion",22, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 52: // comparacion ::= expresionSumRes COMP_MENOR_IGUAL expresionSumRes 
            {
              String RESULT =null;
		int es1left = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int es1right = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		String es1 = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int es2left = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int es2right = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String es2 = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = es1 + "\n" + es2;
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("comparacion",22, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 53: // comparacion ::= expresionSumRes 
            {
              String RESULT =null;
		int esleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int esright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String es = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = es;
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("comparacion",22, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 54: // expresionSumRes ::= expresionSumRes OP_SUMA expresionMultDiv 
            {
              String RESULT =null;
		int esleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int esright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		String es = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int emleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int emright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String em = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = es + "\n" + em;
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresionSumRes",18, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 55: // expresionSumRes ::= expresionSumRes OP_RESTA expresionMultDiv 
            {
              String RESULT =null;
		int esleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int esright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		String es = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int emleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int emright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String em = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = es + "\n" + em;
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresionSumRes",18, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 56: // expresionSumRes ::= expresionMultDiv 
            {
              String RESULT =null;
		int emleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int emright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String em = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = em;
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresionSumRes",18, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 57: // expresionMultDiv ::= expresionMultDiv OP_MULT expresionMenosU 
            {
              String RESULT =null;
		int emleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int emright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		String em = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int emuleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int emuright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String emu = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = em + "\n" + emu;
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresionMultDiv",19, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 58: // expresionMultDiv ::= expresionMultDiv OP_DIV expresionMenosU 
            {
              String RESULT =null;
		int emleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int emright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		String em = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int emuleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int emuright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String emu = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = em + "\n" + emu;
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresionMultDiv",19, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 59: // expresionMultDiv ::= expresionMenosU 
            {
              String RESULT =null;
		int emuleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int emuright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String emu = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = emu;
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresionMultDiv",19, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 60: // expresionMenosU ::= OP_RESTA expresion 
            {
              String RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String e = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = e;
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresionMenosU",21, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 61: // expresionMenosU ::= expresion 
            {
              String RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String e = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = e;
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresionMenosU",21, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 62: // expresion ::= PAR_A expresionOr PAR_C 
            {
              String RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		String e = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		 RESULT = e;
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion",13, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 63: // expresion ::= ID 
            {
              String RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion",13, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 64: // expresion ::= valorLiteral 
            {
              String RESULT =null;
		int vlleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int vlright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String vl = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = vl;
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion",13, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 65: // expresion ::= ID CORCH_A expresionOr CORCH_C 
            {
              String RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		String e = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		 RESULT = e;
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion",13, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 66: // expresion ::= READ_INT PAR_A PAR_C 
            {
              String RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion",13, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 67: // expresion ::= READ_FLOAT PAR_A PAR_C 
            {
              String RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion",13, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 68: // expresion ::= READ_BOOL PAR_A PAR_C 
            {
              String RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion",13, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 69: // expresion ::= sum_acum 
            {
              String RESULT =null;
		int smleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int smright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String sm = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = sm;
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion",13, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 70: // valorLiteral ::= CTE_INT 
            {
              String RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("valorLiteral",23, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 71: // valorLiteral ::= CTE_FLOAT 
            {
              String RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("valorLiteral",23, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 72: // valorLiteral ::= CONST_BOOL 
            {
              String RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("valorLiteral",23, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 73: // valorLiteral ::= CTE_ARREGLO 
            {
              String RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("valorLiteral",23, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 74: // sum_acum ::= SUMA_ACUM PAR_A expresionOr COMA CORCH_A lista_expresiones CORCH_C PAR_C 
            {
              String RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)).right;
		String e = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-5)).value;
		int leleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int leright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		String le = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		
            RESULT = e + "\n" + le;
            
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("sum_acum",20, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-7)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 75: // sum_acum ::= SUMA_ACUM PAR_A expresionOr COMA CORCH_A CORCH_C PAR_C 
            {
              String RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)).right;
		String e = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-4)).value;
		
            RESULT = e;
            
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("sum_acum",20, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-6)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 76: // sum_acum ::= SUMA_ACUM PAR_A expresionOr COMA lista_expresiones PAR_C 
            {
              String RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).right;
		String e = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-3)).value;
		int leleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int leright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		String le = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		
            RESULT = e + "\n" + le;
            
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("sum_acum",20, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 77: // lista_expresiones ::= lista_expresiones COMA expresionOr 
            {
              String RESULT =null;
		int lileft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int liright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		String li = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String e = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
                    RESULT = li + "\n" + e;
                    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("lista_expresiones",14, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 78: // lista_expresiones ::= expresionOr 
            {
              String RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String e = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
                    RESULT = e;
                    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("lista_expresiones",14, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$Parser$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$Parser$do_action(
    int                        CUP$Parser$act_num,
    java_cup.runtime.lr_parser CUP$Parser$parser,
    java.util.Stack            CUP$Parser$stack,
    int                        CUP$Parser$top)
    throws java.lang.Exception
    {
              return CUP$Parser$do_action_part00000000(
                               CUP$Parser$act_num,
                               CUP$Parser$parser,
                               CUP$Parser$stack,
                               CUP$Parser$top);
    }
}

}
