
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Parser;

import java_cup.runtime.*;
import Exception.SyntaxException;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class Parser extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return ParserSym.class;
}

  /** Default constructor. */
  @Deprecated
  public Parser() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public Parser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public Parser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\072\000\002\002\004\000\002\002\006\000\002\003" +
    "\004\000\002\003\002\000\002\004\005\000\002\005\003" +
    "\000\002\005\003\000\002\005\003\000\002\005\003\000" +
    "\002\006\005\000\002\006\003\000\002\007\004\000\002" +
    "\007\003\000\002\010\003\000\002\010\003\000\002\010" +
    "\003\000\002\010\003\000\002\010\003\000\002\010\003" +
    "\000\002\011\005\000\002\012\006\000\002\012\006\000" +
    "\002\014\007\000\002\015\007\000\002\021\005\000\002" +
    "\021\003\000\002\022\005\000\002\022\003\000\002\023" +
    "\004\000\002\023\003\000\002\031\005\000\002\031\005" +
    "\000\002\031\005\000\002\031\005\000\002\031\005\000" +
    "\002\031\005\000\002\031\003\000\002\024\005\000\002" +
    "\024\005\000\002\024\003\000\002\025\005\000\002\025" +
    "\005\000\002\025\003\000\002\027\004\000\002\027\003" +
    "\000\002\016\005\000\002\016\003\000\002\016\003\000" +
    "\002\016\005\000\002\016\005\000\002\016\005\000\002" +
    "\016\003\000\002\033\003\000\002\033\003\000\002\033" +
    "\003\000\002\026\010\000\002\017\005\000\002\017\003" +
    "" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\153\000\004\004\005\001\002\000\004\002\155\001" +
    "\002\000\026\005\ufffe\010\ufffe\012\ufffe\013\ufffe\014\ufffe" +
    "\015\ufffe\016\ufffe\017\ufffe\020\ufffe\026\ufffe\001\002\000" +
    "\026\005\016\010\012\012\023\013\007\014\025\015\013" +
    "\016\027\017\030\020\011\026\017\001\002\000\020\005" +
    "\uffef\010\uffef\012\uffef\013\uffef\014\uffef\025\uffef\026\uffef" +
    "\001\002\000\004\057\150\001\002\000\004\057\ufff9\001" +
    "\002\000\004\052\144\001\002\000\004\057\ufffc\001\002" +
    "\000\020\005\ufff2\010\ufff2\012\ufff2\013\ufff2\014\ufff2\025" +
    "\ufff2\026\ufff2\001\002\000\020\005\016\010\012\012\023" +
    "\013\007\014\025\025\143\026\017\001\002\000\004\052" +
    "\136\001\002\000\004\046\134\001\002\000\020\005\ufff4" +
    "\010\ufff4\012\ufff4\013\ufff4\014\ufff4\025\ufff4\026\ufff4\001" +
    "\002\000\026\005\uffff\010\uffff\012\uffff\013\uffff\014\uffff" +
    "\015\uffff\016\uffff\017\uffff\020\uffff\026\uffff\001\002\000" +
    "\020\005\ufff5\010\ufff5\012\ufff5\013\ufff5\014\ufff5\025\ufff5" +
    "\026\ufff5\001\002\000\020\005\ufff0\010\ufff0\012\ufff0\013" +
    "\ufff0\014\ufff0\025\ufff0\026\ufff0\001\002\000\020\005\ufff3" +
    "\010\ufff3\012\ufff3\013\ufff3\014\ufff3\025\ufff3\026\ufff3\001" +
    "\002\000\004\052\031\001\002\000\020\005\ufff1\010\ufff1" +
    "\012\ufff1\013\ufff1\014\ufff1\025\ufff1\026\ufff1\001\002\000" +
    "\004\057\ufffb\001\002\000\004\057\ufffa\001\002\000\032" +
    "\021\050\022\046\023\041\024\052\026\045\027\040\030" +
    "\043\031\056\035\057\051\037\052\044\061\055\001\002" +
    "\000\054\005\uffce\010\uffce\012\uffce\013\uffce\014\uffce\025" +
    "\uffce\026\uffce\034\uffce\035\uffce\036\uffce\037\uffce\040\uffce" +
    "\041\uffce\042\uffce\043\uffce\044\uffce\045\uffce\047\uffce\050" +
    "\uffce\053\uffce\056\uffce\001\002\000\036\034\uffd7\035\uffd7" +
    "\036\uffd7\037\uffd7\040\uffd7\041\uffd7\042\uffd7\043\uffd7\044" +
    "\uffd7\045\uffd7\047\uffd7\050\uffd7\053\uffd7\056\uffd7\001\002" +
    "\000\036\034\uffda\035\uffda\036\123\037\124\040\uffda\041" +
    "\uffda\042\uffda\043\uffda\044\uffda\045\uffda\047\uffda\050\uffda" +
    "\053\uffda\056\uffda\001\002\000\032\034\115\035\114\040" +
    "\117\041\116\042\113\043\112\044\111\045\110\047\uffdd" +
    "\050\uffdd\053\uffdd\056\uffdd\001\002\000\036\034\uffd5\035" +
    "\uffd5\036\uffd5\037\uffd5\040\uffd5\041\uffd5\042\uffd5\043\uffd5" +
    "\044\uffd5\045\uffd5\047\uffd5\050\uffd5\053\uffd5\056\uffd5\001" +
    "\002\000\030\021\050\022\046\023\041\024\052\026\045" +
    "\027\040\030\043\035\057\051\037\052\044\061\055\001" +
    "\002\000\054\005\uffcd\010\uffcd\012\uffcd\013\uffcd\014\uffcd" +
    "\025\uffcd\026\uffcd\034\uffcd\035\uffcd\036\uffcd\037\uffcd\040" +
    "\uffcd\041\uffcd\042\uffcd\043\uffcd\044\uffcd\045\uffcd\047\uffcd" +
    "\050\uffcd\053\uffcd\056\uffcd\001\002\000\004\052\105\001" +
    "\002\000\054\005\uffd2\010\uffd2\012\uffd2\013\uffd2\014\uffd2" +
    "\025\uffd2\026\uffd2\034\uffd2\035\uffd2\036\uffd2\037\uffd2\040" +
    "\uffd2\041\uffd2\042\uffd2\043\uffd2\044\uffd2\045\uffd2\047\uffd2" +
    "\050\uffd2\053\uffd2\056\uffd2\001\002\000\054\005\uffcc\010" +
    "\uffcc\012\uffcc\013\uffcc\014\uffcc\025\uffcc\026\uffcc\034\uffcc" +
    "\035\uffcc\036\uffcc\037\uffcc\040\uffcc\041\uffcc\042\uffcc\043" +
    "\uffcc\044\uffcc\045\uffcc\047\uffcc\050\uffcc\053\uffcc\056\uffcc" +
    "\001\002\000\030\021\050\022\046\023\041\024\052\026" +
    "\045\027\040\030\043\035\057\051\037\052\044\061\055" +
    "\001\002\000\054\005\uffd3\010\uffd3\012\uffd3\013\uffd3\014" +
    "\uffd3\025\uffd3\026\uffd3\034\uffd3\035\uffd3\036\uffd3\037\uffd3" +
    "\040\uffd3\041\uffd3\042\uffd3\043\uffd3\044\uffd3\045\uffd3\047" +
    "\uffd3\050\uffd3\053\uffd3\056\uffd3\001\002\000\004\052\101" +
    "\001\002\000\010\050\077\053\uffe8\056\uffe8\001\002\000" +
    "\004\052\075\001\002\000\004\053\074\001\002\000\054" +
    "\005\uffcb\010\uffcb\012\uffcb\013\uffcb\014\uffcb\025\uffcb\026" +
    "\uffcb\034\uffcb\035\uffcb\036\uffcb\037\uffcb\040\uffcb\041\uffcb" +
    "\042\uffcb\043\uffcb\044\uffcb\045\uffcb\047\uffcb\050\uffcb\053" +
    "\uffcb\056\uffcb\001\002\000\012\047\072\050\uffe6\053\uffe6" +
    "\056\uffe6\001\002\000\012\047\uffe4\050\uffe4\053\uffe4\056" +
    "\uffe4\001\002\000\004\052\062\001\002\000\004\053\061" +
    "\001\002\000\024\021\050\022\046\023\041\024\052\026" +
    "\045\027\040\030\043\052\044\061\055\001\002\000\036" +
    "\034\uffd6\035\uffd6\036\uffd6\037\uffd6\040\uffd6\041\uffd6\042" +
    "\uffd6\043\uffd6\044\uffd6\045\uffd6\047\uffd6\050\uffd6\053\uffd6" +
    "\056\uffd6\001\002\000\020\005\uffec\010\uffec\012\uffec\013" +
    "\uffec\014\uffec\025\uffec\026\uffec\001\002\000\030\021\050" +
    "\022\046\023\041\024\052\026\045\027\040\030\043\035" +
    "\057\051\037\052\044\061\055\001\002\000\004\056\064" +
    "\001\002\000\030\021\050\022\046\023\041\024\052\026" +
    "\045\027\040\030\043\035\057\051\037\052\044\061\055" +
    "\001\002\000\006\053\070\056\067\001\002\000\006\053" +
    "\uffc8\056\uffc8\001\002\000\030\021\050\022\046\023\041" +
    "\024\052\026\045\027\040\030\043\035\057\051\037\052" +
    "\044\061\055\001\002\000\054\005\uffca\010\uffca\012\uffca" +
    "\013\uffca\014\uffca\025\uffca\026\uffca\034\uffca\035\uffca\036" +
    "\uffca\037\uffca\040\uffca\041\uffca\042\uffca\043\uffca\044\uffca" +
    "\045\uffca\047\uffca\050\uffca\053\uffca\056\uffca\001\002\000" +
    "\006\053\uffc9\056\uffc9\001\002\000\030\021\050\022\046" +
    "\023\041\024\052\026\045\027\040\030\043\035\057\051" +
    "\037\052\044\061\055\001\002\000\010\050\uffe7\053\uffe7" +
    "\056\uffe7\001\002\000\020\005\uffed\010\uffed\012\uffed\013" +
    "\uffed\014\uffed\025\uffed\026\uffed\001\002\000\004\053\076" +
    "\001\002\000\054\005\uffd1\010\uffd1\012\uffd1\013\uffd1\014" +
    "\uffd1\025\uffd1\026\uffd1\034\uffd1\035\uffd1\036\uffd1\037\uffd1" +
    "\040\uffd1\041\uffd1\042\uffd1\043\uffd1\044\uffd1\045\uffd1\047" +
    "\uffd1\050\uffd1\053\uffd1\056\uffd1\001\002\000\030\021\050" +
    "\022\046\023\041\024\052\026\045\027\040\030\043\035" +
    "\057\051\037\052\044\061\055\001\002\000\006\053\uffe9" +
    "\056\uffe9\001\002\000\004\053\102\001\002\000\054\005" +
    "\uffd0\010\uffd0\012\uffd0\013\uffd0\014\uffd0\025\uffd0\026\uffd0" +
    "\034\uffd0\035\uffd0\036\uffd0\037\uffd0\040\uffd0\041\uffd0\042" +
    "\uffd0\043\uffd0\044\uffd0\045\uffd0\047\uffd0\050\uffd0\053\uffd0" +
    "\056\uffd0\001\002\000\004\053\104\001\002\000\054\005" +
    "\uffd4\010\uffd4\012\uffd4\013\uffd4\014\uffd4\025\uffd4\026\uffd4" +
    "\034\uffd4\035\uffd4\036\uffd4\037\uffd4\040\uffd4\041\uffd4\042" +
    "\uffd4\043\uffd4\044\uffd4\045\uffd4\047\uffd4\050\uffd4\053\uffd4" +
    "\056\uffd4\001\002\000\004\053\106\001\002\000\054\005" +
    "\uffcf\010\uffcf\012\uffcf\013\uffcf\014\uffcf\025\uffcf\026\uffcf" +
    "\034\uffcf\035\uffcf\036\uffcf\037\uffcf\040\uffcf\041\uffcf\042" +
    "\uffcf\043\uffcf\044\uffcf\045\uffcf\047\uffcf\050\uffcf\053\uffcf" +
    "\056\uffcf\001\002\000\012\047\uffe5\050\uffe5\053\uffe5\056" +
    "\uffe5\001\002\000\026\021\050\022\046\023\041\024\052" +
    "\026\045\027\040\030\043\035\057\052\044\061\055\001" +
    "\002\000\026\021\050\022\046\023\041\024\052\026\045" +
    "\027\040\030\043\035\057\052\044\061\055\001\002\000" +
    "\026\021\050\022\046\023\041\024\052\026\045\027\040" +
    "\030\043\035\057\052\044\061\055\001\002\000\026\021" +
    "\050\022\046\023\041\024\052\026\045\027\040\030\043" +
    "\035\057\052\044\061\055\001\002\000\026\021\050\022" +
    "\046\023\041\024\052\026\045\027\040\030\043\035\057" +
    "\052\044\061\055\001\002\000\026\021\050\022\046\023" +
    "\041\024\052\026\045\027\040\030\043\035\057\052\044" +
    "\061\055\001\002\000\026\021\050\022\046\023\041\024" +
    "\052\026\045\027\040\030\043\035\057\052\044\061\055" +
    "\001\002\000\026\021\050\022\046\023\041\024\052\026" +
    "\045\027\040\030\043\035\057\052\044\061\055\001\002" +
    "\000\016\034\115\035\114\047\uffe3\050\uffe3\053\uffe3\056" +
    "\uffe3\001\002\000\016\034\115\035\114\047\uffe2\050\uffe2" +
    "\053\uffe2\056\uffe2\001\002\000\036\034\uffdc\035\uffdc\036" +
    "\123\037\124\040\uffdc\041\uffdc\042\uffdc\043\uffdc\044\uffdc" +
    "\045\uffdc\047\uffdc\050\uffdc\053\uffdc\056\uffdc\001\002\000" +
    "\026\021\050\022\046\023\041\024\052\026\045\027\040" +
    "\030\043\035\057\052\044\061\055\001\002\000\026\021" +
    "\050\022\046\023\041\024\052\026\045\027\040\030\043" +
    "\035\057\052\044\061\055\001\002\000\036\034\uffd8\035" +
    "\uffd8\036\uffd8\037\uffd8\040\uffd8\041\uffd8\042\uffd8\043\uffd8" +
    "\044\uffd8\045\uffd8\047\uffd8\050\uffd8\053\uffd8\056\uffd8\001" +
    "\002\000\036\034\uffd9\035\uffd9\036\uffd9\037\uffd9\040\uffd9" +
    "\041\uffd9\042\uffd9\043\uffd9\044\uffd9\045\uffd9\047\uffd9\050" +
    "\uffd9\053\uffd9\056\uffd9\001\002\000\036\034\uffdb\035\uffdb" +
    "\036\123\037\124\040\uffdb\041\uffdb\042\uffdb\043\uffdb\044" +
    "\uffdb\045\uffdb\047\uffdb\050\uffdb\053\uffdb\056\uffdb\001\002" +
    "\000\016\034\115\035\114\047\uffdf\050\uffdf\053\uffdf\056" +
    "\uffdf\001\002\000\016\034\115\035\114\047\uffde\050\uffde" +
    "\053\uffde\056\uffde\001\002\000\016\034\115\035\114\047" +
    "\uffe1\050\uffe1\053\uffe1\056\uffe1\001\002\000\016\034\115" +
    "\035\114\047\uffe0\050\uffe0\053\uffe0\056\uffe0\001\002\000" +
    "\024\021\050\022\046\023\041\024\052\026\045\027\040" +
    "\030\043\052\044\061\055\001\002\000\020\005\uffee\010" +
    "\uffee\012\uffee\013\uffee\014\uffee\025\uffee\026\uffee\001\002" +
    "\000\024\021\050\022\046\023\041\024\052\026\045\027" +
    "\040\030\043\052\044\061\055\001\002\000\004\053\140" +
    "\001\002\000\016\005\016\010\012\012\023\013\007\014" +
    "\025\026\017\001\002\000\020\005\016\010\012\012\023" +
    "\013\007\014\025\025\uffeb\026\017\001\002\000\020\005" +
    "\ufff6\010\ufff6\012\ufff6\013\ufff6\014\ufff6\025\ufff6\026\ufff6" +
    "\001\002\000\004\002\000\001\002\000\024\021\050\022" +
    "\046\023\041\024\052\026\045\027\040\030\043\052\044" +
    "\061\055\001\002\000\004\053\146\001\002\000\016\005" +
    "\016\010\012\012\023\013\007\014\025\026\017\001\002" +
    "\000\020\005\016\010\012\012\023\013\007\014\025\025" +
    "\uffea\026\017\001\002\000\004\026\151\001\002\000\030" +
    "\005\ufff7\010\ufff7\012\ufff7\013\ufff7\014\ufff7\015\ufff7\016" +
    "\ufff7\017\ufff7\020\ufff7\026\ufff7\056\ufff7\001\002\000\030" +
    "\005\ufffd\010\ufffd\012\ufffd\013\ufffd\014\ufffd\015\ufffd\016" +
    "\ufffd\017\ufffd\020\ufffd\026\ufffd\056\153\001\002\000\004" +
    "\026\154\001\002\000\030\005\ufff8\010\ufff8\012\ufff8\013" +
    "\ufff8\014\ufff8\015\ufff8\016\ufff8\017\ufff8\020\ufff8\026\ufff8" +
    "\056\ufff8\001\002\000\004\002\001\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\153\000\004\002\003\001\001\000\002\001\001\000" +
    "\004\003\005\001\001\000\022\004\020\005\007\007\014" +
    "\010\021\011\017\012\023\014\013\015\025\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\014\010" +
    "\141\011\017\012\023\014\013\015\025\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\026\016\035\021\050\022\046\023\052" +
    "\024\034\025\033\026\031\027\032\031\053\033\041\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\022\016\035\023" +
    "\106\024\034\025\033\026\031\027\032\031\053\033\041" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\026\016\035\021\102\022\046" +
    "\023\052\024\034\025\033\026\031\027\032\031\053\033" +
    "\041\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\010\016\057\026\031\033\041\001" +
    "\001\000\002\001\001\000\002\001\001\000\026\016\035" +
    "\021\062\022\046\023\052\024\034\025\033\026\031\027" +
    "\032\031\053\033\041\001\001\000\002\001\001\000\030" +
    "\016\035\017\064\021\065\022\046\023\052\024\034\025" +
    "\033\026\031\027\032\031\053\033\041\001\001\000\002" +
    "\001\001\000\002\001\001\000\026\016\035\021\070\022" +
    "\046\023\052\024\034\025\033\026\031\027\032\031\053" +
    "\033\041\001\001\000\002\001\001\000\002\001\001\000" +
    "\024\016\035\022\072\023\052\024\034\025\033\026\031" +
    "\027\032\031\053\033\041\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\026" +
    "\016\035\021\077\022\046\023\052\024\034\025\033\026" +
    "\031\027\032\031\053\033\041\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\016\016\035\024\132\025\033\026\031\027" +
    "\032\033\041\001\001\000\016\016\035\024\131\025\033" +
    "\026\031\027\032\033\041\001\001\000\016\016\035\024" +
    "\130\025\033\026\031\027\032\033\041\001\001\000\016" +
    "\016\035\024\127\025\033\026\031\027\032\033\041\001" +
    "\001\000\014\016\035\025\126\026\031\027\032\033\041" +
    "\001\001\000\014\016\035\025\121\026\031\027\032\033" +
    "\041\001\001\000\016\016\035\024\120\025\033\026\031" +
    "\027\032\033\041\001\001\000\016\016\035\024\117\025" +
    "\033\026\031\027\032\033\041\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\012\016\035\026" +
    "\031\027\125\033\041\001\001\000\012\016\035\026\031" +
    "\027\124\033\041\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\010\016\134\026" +
    "\031\033\041\001\001\000\002\001\001\000\010\016\136" +
    "\026\031\033\041\001\001\000\002\001\001\000\016\007" +
    "\140\010\021\011\017\012\023\014\013\015\025\001\001" +
    "\000\014\010\141\011\017\012\023\014\013\015\025\001" +
    "\001\000\002\001\001\000\002\001\001\000\010\016\144" +
    "\026\031\033\041\001\001\000\002\001\001\000\016\007" +
    "\146\010\021\011\017\012\023\014\013\015\025\001\001" +
    "\000\014\010\141\011\017\012\023\014\013\015\025\001" +
    "\001\000\004\006\151\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$Parser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$Parser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$Parser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



    public void syntax_error(Symbol s){
        // Esto solo imprime un aviso temporal en consola
        System.out.println("Aviso: Error sintáctico cerca de la línea " + (s.left + 1));
    }

    public void unrecovered_syntax_error(Symbol s) throws java.lang.Exception{
        // Construimos el mensaje y LANZAMOS la excepción
        String mensaje = "Error en la linea " + (s.left + 1) + " Columna " + s.right + ". Valor simbolo '" + s.value + "' no esperado.";

        // Lanzamos la excepción directamente
        throw new SyntaxException(mensaje);
    }


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$Parser$actions {
  private final Parser parser;

  /** Constructor */
  CUP$Parser$actions(Parser parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$Parser$do_action_part00000000(
    int                        CUP$Parser$act_num,
    java_cup.runtime.lr_parser CUP$Parser$parser,
    java.util.Stack            CUP$Parser$stack,
    int                        CUP$Parser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$Parser$result;

      /* select the action based on the action number */
      switch (CUP$Parser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= program EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		String start_val = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		RESULT = start_val;
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$Parser$parser.done_parsing();
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // program ::= PROGRAM bloque_declaraciones bloque_sentencias FIN 
            {
              String RESULT =null;
		 RESULT = "Programa valido. Estructura y matematicas correctas!"; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("program",0, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // bloque_declaraciones ::= bloque_declaraciones declaracion 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("bloque_declaraciones",1, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // bloque_declaraciones ::= 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("bloque_declaraciones",1, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // declaracion ::= tipo DOS_PUNTOS lista_ids 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("declaracion",2, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // tipo ::= TYPE_INT 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("tipo",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // tipo ::= TYPE_FLOAT 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("tipo",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // tipo ::= TYPE_BOOL 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("tipo",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // tipo ::= TYPE_ARRAY 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("tipo",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // lista_ids ::= lista_ids COMA ID 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("lista_ids",4, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // lista_ids ::= ID 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("lista_ids",4, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // bloque_sentencias ::= bloque_sentencias sentencia 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("bloque_sentencias",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // bloque_sentencias ::= sentencia 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("bloque_sentencias",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // sentencia ::= asignacion 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("sentencia",6, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // sentencia ::= impresion 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("sentencia",6, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // sentencia ::= sentencia_if 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("sentencia",6, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // sentencia ::= sentencia_while 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("sentencia",6, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // sentencia ::= BREAK 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("sentencia",6, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // sentencia ::= CONTINUE 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("sentencia",6, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // asignacion ::= ID ASIG expresion 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("asignacion",7, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // impresion ::= PRINT PAR_A expresionOr PAR_C 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("impresion",8, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // impresion ::= PRINT PAR_A CTE_STR PAR_C 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("impresion",8, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // sentencia_if ::= IF PAR_A expresion PAR_C bloque_sentencias 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("sentencia_if",10, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // sentencia_while ::= WHILE PAR_A expresion PAR_C bloque_sentencias 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("sentencia_while",11, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // expresionOr ::= expresionAnd OR expresionOr 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresionOr",15, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // expresionOr ::= expresionAnd 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresionOr",15, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // expresionAnd ::= expresionNot AND expresionAnd 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresionAnd",16, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // expresionAnd ::= expresionNot 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresionAnd",16, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // expresionNot ::= NOT expresionNot 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresionNot",17, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // expresionNot ::= comparacion 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresionNot",17, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // comparacion ::= expresionSumRes COMP_IGUAL expresionSumRes 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("comparacion",23, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // comparacion ::= expresionSumRes COMP_DISTINTO expresionSumRes 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("comparacion",23, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // comparacion ::= expresionSumRes COMP_MAYOR expresionSumRes 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("comparacion",23, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // comparacion ::= expresionSumRes COMP_MENOR expresionSumRes 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("comparacion",23, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // comparacion ::= expresionSumRes COMP_MAYOR_IGUAL expresionSumRes 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("comparacion",23, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // comparacion ::= expresionSumRes COMP_MENOR_IGUAL expresionSumRes 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("comparacion",23, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // comparacion ::= expresionSumRes 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("comparacion",23, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // expresionSumRes ::= expresionSumRes OP_SUMA expresionMultDiv 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresionSumRes",18, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // expresionSumRes ::= expresionSumRes OP_RESTA expresionMultDiv 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresionSumRes",18, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // expresionSumRes ::= expresionMultDiv 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresionSumRes",18, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // expresionMultDiv ::= expresionMultDiv OP_MULT expresionMenosU 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresionMultDiv",19, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // expresionMultDiv ::= expresionMultDiv OP_DIV expresionMenosU 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresionMultDiv",19, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // expresionMultDiv ::= expresionMenosU 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresionMultDiv",19, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // expresionMenosU ::= OP_RESTA expresion 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresionMenosU",21, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // expresionMenosU ::= expresion 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresionMenosU",21, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // expresion ::= PAR_A expresionOr PAR_C 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion",12, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // expresion ::= ID 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion",12, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // expresion ::= valorLiteral 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion",12, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 48: // expresion ::= READ_INT PAR_A PAR_C 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion",12, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 49: // expresion ::= READ_FLOAT PAR_A PAR_C 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion",12, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 50: // expresion ::= READ_BOOL PAR_A PAR_C 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion",12, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 51: // expresion ::= sum_acum 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion",12, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 52: // valorLiteral ::= CTE_INT 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("valorLiteral",25, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 53: // valorLiteral ::= CTE_FLOAT 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("valorLiteral",25, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 54: // valorLiteral ::= CONST_BOOL 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("valorLiteral",25, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 55: // sum_acum ::= SUMA_ACUM PAR_A expresionOr COMA lista_expresiones PAR_C 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("sum_acum",20, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 56: // lista_expresiones ::= lista_expresiones COMA expresionOr 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("lista_expresiones",13, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 57: // lista_expresiones ::= expresionOr 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("lista_expresiones",13, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$Parser$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$Parser$do_action(
    int                        CUP$Parser$act_num,
    java_cup.runtime.lr_parser CUP$Parser$parser,
    java.util.Stack            CUP$Parser$stack,
    int                        CUP$Parser$top)
    throws java.lang.Exception
    {
              return CUP$Parser$do_action_part00000000(
                               CUP$Parser$act_num,
                               CUP$Parser$parser,
                               CUP$Parser$stack,
                               CUP$Parser$top);
    }
}

}
