//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Parser;

import Exception.SyntaxException;
import java_cup.runtime.ComplexSymbolFactory;
import java_cup.runtime.Scanner;
import java_cup.runtime.Symbol;
import java_cup.runtime.SymbolFactory;

/**
 * Minimal parser aligned with the current CUP adapter/token set.
 *
 * Current contract:
 * - Program must start with PROGRAM
 * - Program must finish with FIN
 * - Intermediate tokens are accepted while full grammar is completed
 */
public class Parser {

    private final Scanner scanner;
    private final SymbolFactory symbolFactory;

    public Parser(Scanner scanner, SymbolFactory symbolFactory) {
        this.scanner = scanner;
        this.symbolFactory = (symbolFactory != null) ? symbolFactory : new ComplexSymbolFactory();
    }

    public Symbol parse() throws Exception {
        Symbol first = scanner.next_token();
        if (first == null || first.sym == ParserSym.EOF) {
            throw new SyntaxException("Se esperaba PROGRAM al inicio, pero se encontro EOF");
        }
        if (first.sym != ParserSym.PROGRAM) {
            throw new SyntaxException(buildExpectedMessage("PROGRAM", first));
        }

        Symbol current;
        Symbol fin = null;
        while ((current = scanner.next_token()) != null) {
            if (current.sym == ParserSym.FIN) {
                fin = current;
                break;
            }
            if (current.sym == ParserSym.EOF) {
                break;
            }
        }

        if (fin == null) {
            throw new SyntaxException("Se esperaba FIN para cerrar el programa");
        }

        Symbol tail = scanner.next_token();
        if (tail != null && tail.sym != ParserSym.EOF) {
            throw new SyntaxException("Se encontraron tokens despues de FIN");
        }

        // Avoid ComplexSymbol casts when scanner provides plain Symbol instances.
        return new Symbol(ParserSym.PROGRAM, first.left, fin.right, "Programa valido");
    }

    private String buildExpectedMessage(String expected, Symbol found) {
        String foundName = (found.sym >= 0 && found.sym < ParserSym.terminalNames.length)
                ? ParserSym.terminalNames[found.sym]
                : String.valueOf(found.sym);
        return "Se esperaba " + expected + " pero se encontro " + foundName;
    }
}
