
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Parser;

/** CUP generated class containing symbol constants. */
public class ParserSym {
  /* terminals */
  public static final int CTE_ARREGLO = 19;
  public static final int COMP_MENOR_IGUAL = 31;
  public static final int TYPE_ARRAY = 14;
  public static final int SUMA_ACUM = 46;
  public static final int CTE_FLOAT = 22;
  public static final int COMP_IGUAL = 28;
  public static final int DOS_PUNTOS = 43;
  public static final int CONTINUE = 8;
  public static final int OP_DIV = 27;
  public static final int COMP_DISTINTO = 29;
  public static final int NOT = 37;
  public static final int AND = 35;
  public static final int OR = 36;
  public static final int COMP_MENOR = 33;
  public static final int TYPE_INT = 11;
  public static final int UMENOS = 47;
  public static final int IF = 2;
  public static final int ID = 20;
  public static final int EOF = 0;
  public static final int COMP_MAYOR = 32;
  public static final int ASIG = 34;
  public static final int READ_FLOAT = 16;
  public static final int error = 1;
  public static final int PROGRAM = 10;
  public static final int COMA = 42;
  public static final int OP_MULT = 26;
  public static final int PAR_C = 39;
  public static final int OP_RESTA = 25;
  public static final int PAR_A = 38;
  public static final int BREAK = 7;
  public static final int CONST_BOOL = 18;
  public static final int TYPE_FLOAT = 12;
  public static final int ALT_WHILE = 6;
  public static final int READ_INT = 15;
  public static final int ELSE = 4;
  public static final int CTE_STR = 23;
  public static final int V_DEDENT = 45;
  public static final int WHILE = 5;
  public static final int CTE_INT = 21;
  public static final int V_INDENT = 44;
  public static final int OP_SUMA = 24;
  public static final int COMP_MAYOR_IGUAL = 30;
  public static final int TYPE_BOOL = 13;
  public static final int CORCH_C = 41;
  public static final int READ_BOOL = 17;
  public static final int CORCH_A = 40;
  public static final int ELIF = 3;
  public static final int PRINT = 9;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "IF",
  "ELIF",
  "ELSE",
  "WHILE",
  "ALT_WHILE",
  "BREAK",
  "CONTINUE",
  "PRINT",
  "PROGRAM",
  "TYPE_INT",
  "TYPE_FLOAT",
  "TYPE_BOOL",
  "TYPE_ARRAY",
  "READ_INT",
  "READ_FLOAT",
  "READ_BOOL",
  "CONST_BOOL",
  "CTE_ARREGLO",
  "ID",
  "CTE_INT",
  "CTE_FLOAT",
  "CTE_STR",
  "OP_SUMA",
  "OP_RESTA",
  "OP_MULT",
  "OP_DIV",
  "COMP_IGUAL",
  "COMP_DISTINTO",
  "COMP_MAYOR_IGUAL",
  "COMP_MENOR_IGUAL",
  "COMP_MAYOR",
  "COMP_MENOR",
  "ASIG",
  "AND",
  "OR",
  "NOT",
  "PAR_A",
  "PAR_C",
  "CORCH_A",
  "CORCH_C",
  "COMA",
  "DOS_PUNTOS",
  "V_INDENT",
  "V_DEDENT",
  "SUMA_ACUM",
  "UMENOS"
  };
}

